### ISSUE TITLE
I am feeling very lucky makes impossible predictions

### ISSUE THREAD

**Issue by nathansamson** [joeri/wk-predictions-rs#2]
![image](https://user-images.githubusercontent.com/93735/42125019-dfbf78c2-7c6e-11e8-9ba1-9e117e416091.png)

So the match is going to take 120 minutes, and the result is 4-0.
This means all 4 goals need to be scored in the last 30 minutes (otherwise the match would have ended after 90 minutes).

But it also guessed the first goal would be at minute 60.

**Comment by joerixaop** [comment]
Solved by 9bcf162

**Comment by joeri** [comment]
Closed by commit 9bcf162
